# Generated by Django 3.0.8 on 2020-07-07 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('maf_date', models.DateField()),
                ('exp_date', models.DateField(default=datetime.date(2020, 1, 1))),
            ],
        ),
    ]
